FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn -Pprod clean verify

FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
